issue: _translated_1_
issues: _translated_2_
Issue: _translated_3_
Issues: _translated_4_
issue_or_issues: _translated_5_
parent_task: _translated_6_
Parent_task: _translated_7_
Parent_tasks: _translated_8_
issue_subtask_or_subtasks: _translated_9_
issue_subtasks: _translated_10_
issue_Subtask: _translated_11_
issue_Subtasks: _translated_12_
issue_note: _translated_13_
issue_notes: _translated_14_
issue_Note: _translated_15_
issue_Notes: _translated_16_
issue_watcher: _translated_17_1_
issue_watchers: _translated_17_
issue_Watcher: _translated_18_
issue_Watchers: _translated_19_
issue_Watched: _translated_20_
issue_watch: _translated_21_
Issue_tracking: _translated_22_
issue_tracker: _translated_23_
issue_Tracker: _translated_24_
issue_trackers: _translated_25_
issue_Trackers: _translated_26_
issue_tracker_or_trackers: _translated_27_
issue_Status: _translated_28_
issue_status: _translated_29_
issue_statuses: _translated_30_
issue_assignee: _translated_31_
issue_Assignee: _translated_32_
issue_Assigned: _translated_33_
issue_assigned: _translated_34_
issue_assigned_to: _translated_35_
issue_am_assigned_to: _translated_36_
issue_assignment_to: _translated_37_
issue_priority: _translated_38_1_
issue_Priority: _translated_38_
issue_priorities: _translated_39_
issue_category: _translated_40_
issue_Category: _translated_41_
issue_categories: _translated_42_
issue_open: _translated_43_
issue_Open: _translated_44_
issues_open: _translated_45_
issue_closed: _translated_46_
issues_closed: _translated_47_
issue_Closed: _translated_48_
project: _translated_49_
projects: _translated_50_
Project: _translated_51_
Projects: _translated_52_
subproject: _translated_53_
subprojects: _translated_54_
Subproject: _translated_55_
Subprojects: _translated_56_
subproject_or_subprojects: _translated_57_
