issue: _translated 1_
issues: _translated 2_
Issue: _translated 3_
Issues: _translated 4_
issue_or_issues: _translated 5_
parent_task: _translated 6_
Parent_task: _translated 7_
Parent_tasks: _translated 8_
issue_subtask_or_subtasks: _translated 9_
issue_subtasks: _translated 10_
issue_Subtask: _translated 11_
issue_Subtasks: _translated 12_
issue_note: _translated 13_
issue_notes: _translated 14_
issue_Note: _translated 15_
issue_Notes: _translated 16_
issue_watchers: _translated 17_
issue_Watcher: _translated 18_
issue_Watchers: _translated 19_
issue_Watched: _translated 20_
issue_watch: _translated 21_
Issue_tracking: _translated 22_
issue_tracker: _translated 23_
issue_Tracker: _translated 24_
issue_trackers: _translated 25_
issue_Trackers: _translated 26_
issue_tracker_or_trackers: _translated 27_
issue_Status: _translated 28_
issue_status: _translated 29_
issue_statuses: _translated 30_
issue_assignee: _translated 31_
issue_Assignee: _translated 32_
issue_Assigned: _translated 33_
issue_assigned: _translated 34_
issue_assigned_to: _translated 35_
issue_am_assigned_to: _translated 36_
issue_assignment_to: _translated 37_
issue_Priority: _translated 38_
issue_priorities: _translated 39_
issue_category: _translated 40_
issue_Category: _translated 41_
issue_categories: _translated 42_
issue_open: _translated 43_
issue_Open: _translated 44_
issues_open: _translated 45_
issue_closed: _translated 46_
issues_closed: _translated 47_
issue_Closed: _translated 48_
project: _translated 49_
projects: _translated 50_
Project: _translated 51_
Projects: _translated 52_
subproject: _translated 53_
subprojects: _translated 54_
Subproject: _translated 55_
Subprojects: _translated 56_
subproject_or_subprojects: _translated 57_
