segnalazione: _translated 1_
segnalazioni: _translated 2_
Segnalazione: _translated 3_
Segnalazioni: _translated 4_
sottosegnalazione: _translated 5_
sottosegnalazioni: _translated 6_
Sottosegnalazioni: _translated 7_
sottosegnalazione_La: _translated 8_
sottosegnalazione_dalle: _translated 9_
sottosegnalazione_spostata: _translated 10_
segnalazione_Madre: _translated 11_
segnalazione_madre: _translated 12_
segnalazione_campo_Madre: _translated 13_
segnalazione_la: _translated 14_
segnalazione_la_pronome: _translated 15_
segnalazione_La: _translated 16_
segnalazione_le: _translated 17_
segnalazione_una: _translated 18_
segnalazione_Una: _translated 19_
segnalazione_della: _translated 20_
segnalazione_delle: _translated 21_
segnalazione_sulle: _translated 22_
segnalazione_alle: _translated 23_
segnalazione_una_delle_sue: _translated 24_
segnalazione_Le_mie: _translated 25_
segnalazione_questa: _translated 26_
segnalazione_Alcune: _translated 27_
segnalazione_proprie: _translated 28_
segnalazione_stata_aggiornata: _translated 29_
segnalazione_state_assegnate: _translated 30_
segnalazione_stata_trovata: _translated 31_
segnalazione_aperta: _translated 32_
segnalazione_aperte: _translated 33_
segnalazione_riaperta: _translated 34_
segnalazione_chiusa: _translated 35_
segnalazione_Chiusa: _translated 36_
segnalazione_chiuse: _translated 37_
segnalazione_Chiudi: _translated 38_
segnalazione_chiusura: _translated 39_
segnalazione_figlia: _translated 40_
segnalazione_mostrate: _translated 41_
segnalazione_correlate: _translated 42_
segnalazione_completate: _translated 43_
segnalazione_pubbliche: _translated 44_
segnalazione_Privata: _translated 45_
segnalazione_private: _translated 46_
segnalazione_relative: _translated 47_
segnalazione_nuove: _translated 48_
segnalazione_Nuova: _translated 49_
segnalazione_tutte: _translated 50_
segnalazione_Tutte: _translated 51_
segnalazione_selezionate: _translated 52_
segnalazione_aggiunte: _translated 53_
segnalazione_aggiornate: _translated 54_
segnalazione_referenziate: _translated 55_
segnalazione_risolte: _translated 56_
segnalazione_rimossa: _translated 57_
segnalazione_creata: _translated 58_
segnalazione_Creata: _translated 59_
segnalazione_create: _translated 60_
segnalazione_Aggiornata: _translated 61_
segnalazione_copiate: _translated 62_
segnalazione_osservate: _translated 63_
segnalazione_osservi: _translated 64_
segnalazione_Osserva: _translated 65_
segnalazione_osservatore: _translated 66_
segnalazione_Osservatore: _translated 67_
segnalazione_osservatori: _translated 68_
segnalazione_Osservatori: _translated 69_
segnalazione_osservatore_un: _translated 70_
segnalazione_Dimentica: _translated 71_
segnalazione_assegnare: _translated 72_
segnalazione_assegnata: _translated 73_
segnalazione_Assegnata: _translated 74_
segnalazione_assegnate: _translated 75_
segnalazione_assegnare: _translated 76_
segnalazione_assegnatario: _translated 77_
segnalazione_Assegnatario: _translated 78_
segnalazione_Assegnatari: _translated 79_
segnalazione_Assegnatario_agg: _translated 80_
segnalazione_assegnatario_lo: _translated 81_
segnalazione_assegn_dello: _translated 82_
segnalazione_categoria: _translated 83_
segnalazione_categorie: _translated 84_
segnalazione_Categoria: _translated 85_
segnalazione_Categorie: _translated 86_
segnalazione_categoria_la: _translated 87_
segnalazione_categoria_Nuova: _translated 88_
segnalazione_categoria_questa: _translated 89_
segnalazione_stato: _translated 90_
segnalazione_stati: _translated 91_
segnalazione_Stato: _translated 92_
segnalazione_Stati: _translated 93_
segnalazione_stato_lo: _translated 94_
segnalazione_stato_Nessuno: _translated 95_
segnalazione_stato_Nuovo: _translated 96_
segnalazione_stati_Nuovi: _translated 97_
segnalazione_stato_applicato: _translated 98_
segnalazione_stato_aggiornato: _translated 99_
segnalazione_stato_predefinito: _translated 100_
segnalazione_stato_configurato: _translated 101_
segnalazione_stato_attivo: _translated 102_
segnalazione_stato_usati: _translated 103_
segnalazione_stato_In_elab: _translated 104_
segnalazione_stato_Risolto: _translated 105_
segnalazione_stato_Commenti: _translated 106_
segnalazione_stato_Chiuso: _translated 107_
segnalazione_stato_Rifiutato: _translated 108_
segnalazione_nota: _translated 109_
segnalazione_note: _translated 110_
segnalazione_Nota: _translated 111_
segnalazione_Note: _translated 112_
segnalazione_nota_la: _translated 113_
segnalazione_nota_le: _translated 114_
segnalazione_nota_una: _translated 115_
segnalazione_nota_le_mie: _translated 116_
segnalazione_nota_aggiunta: _translated 117_
segnalazione_nota_salvata: _translated 118_
segnalazione_nota_precedenti: _translated 119_
segnalazione_nota_mantenute: _translated 120_
segnalazione_nota_private: _translated 121_
segnalazione_Tracker: _translated 122_
segnalazione_tracker: _translated 123_
segnalazione_tracker_plurale: _translated 124_
segnalazione_Tracker_plurale: _translated 125_
segnalazione_tracker_i: _translated 126_
segnalazione_tracker_Nuovo: _translated 127_
segnalazione_tracker_un: _translated 128_
segnalazione_tracker_questo: _translated 129_
segnalazione_tracker_Questo: _translated 130_
segnalazione_tracker_nessun: _translated 131_
segnalazione_tracker_Tutti: _translated 132_
segnalazione_tracker_associato: _translated 133_
segnalazione_tracker_eliminato: _translated 134_
segnalazione_tracker_finali: _translated 135_
segnalazione_Priorita: _translated 136_
segnalazione_priorita_agg: _translated 137_
tempo_Attivita: _translated 138_
diario_Attivita: _translated 139_
progetto: _translated 140_
progetti: _translated 141_
Progetto: _translated 142_
Progetti: _translated 143_
progetto_il: _translated 144_
progetto_Il: _translated 145_
progetto_i: _translated 146_
progetto_I: _translated 147_
progetto_un: _translated 148_
progetto_al: _translated 149_
progetto_dei: _translated 150_
progetto_del: _translated 151_
progetto_nel: _translated 152_
progetto_degli: _translated 153_
progetto_allo_stesso: _translated 154_
progetto_ad_uno_dei_miei: _translated 155_
progetto_i_suoi: _translated 156_
progetto_miei: _translated 157_
progetto_tutti: _translated 158_
progetto_Tutti: _translated 159_
progetto_nuovi: _translated 160_
progetto_Nuovo: _translated 161_
progetto_altri: _translated 162_
progetto_nessun: _translated 163_
progetto_questo: _translated 164_
progetto_Questo: _translated 165_
progetto_Ultimi: _translated 166_
progetto_registrati: _translated 167_
progetto_pubblici: _translated 168_
progetto_selezionati: _translated 169_
progetto_visibili: _translated 170_
progetto_chiuso: _translated 171_
progetto_chiusi: _translated 172_
progetto_archiviato: _translated 173_
progetto_attivo: _translated 174_
progetto_padre: _translated 175_
progetto_stato: _translated 176_
progetto_privo: _translated 177_
progetto_diversi: _translated 178_
sottoprogetto: _translated 179_
Sottoprogetto: _translated 180_
sottoprogetti: _translated 181_
Sottoprogetti: _translated 182_
ruolo_Gestore: _translated 183_
ruolo_Sviluppatore: _translated 184_
ruolo_Segnalatore: _translated 185_
