segnalazione: _translated_1_
segnalazioni: _translated_2_
Segnalazione: _translated_3_
Segnalazioni: _translated_4_
sottosegnalazione: _translated_5_
sottosegnalazioni: _translated_6_
Sottosegnalazioni: _translated_7_
sottosegnalazione_La: _translated_8_
sottosegnalazione_dalle: _translated_9_
sottosegnalazione_spostata: _translated_10_
segnalazione_Madre: _translated_11_
segnalazione_madre: _translated_12_
segnalazione_campo_Madre: _translated_13_
segnalazione_la: _translated_14_
segnalazione_la_pronome: _translated_15_
segnalazione_La: _translated_16_
segnalazione_le: _translated_17_
segnalazione_una: _translated_18_
segnalazione_Una: _translated_19_
segnalazione_della: _translated_20_
segnalazione_delle: _translated_21_
segnalazione_sulle: _translated_22_
segnalazione_alle: _translated_23_
segnalazione_una_delle_sue: _translated_24_
segnalazione_Le_mie: _translated_25_
segnalazione_questa: _translated_26_
segnalazione_Alcune: _translated_27_
segnalazione_proprie: _translated_28_
segnalazione_stata_aggiornata: _translated_29_
segnalazione_state_assegnate: _translated_30_
segnalazione_stata_trovata: _translated_31_
segnalazione_aperta: _translated_32_
segnalazione_aperte: _translated_33_
segnalazione_riaperta: _translated_34_
segnalazione_chiusa: _translated_35_
segnalazione_Chiusa: _translated_36_
segnalazione_chiuse: _translated_37_
segnalazione_Chiudi: _translated_38_
segnalazione_chiusura: _translated_39_
segnalazione_figlia: _translated_40_
segnalazione_mostrate: _translated_41_
segnalazione_correlate: _translated_42_
segnalazione_completate: _translated_43_
segnalazione_pubbliche: _translated_44_
segnalazione_Privata: _translated_45_
segnalazione_private: _translated_46_
segnalazione_relative: _translated_47_
segnalazione_nuove: _translated_48_
segnalazione_Nuova: _translated_49_
segnalazione_tutte: _translated_50_
segnalazione_Tutte: _translated_51_
segnalazione_selezionate: _translated_52_
segnalazione_aggiunte: _translated_53_
segnalazione_aggiornate: _translated_54_
segnalazione_referenziate: _translated_55_
segnalazione_risolte: _translated_56_
segnalazione_rimossa: _translated_57_
segnalazione_creata: _translated_58_
segnalazione_Creata: _translated_59_
segnalazione_create: _translated_60_
segnalazione_Aggiornata: _translated_61_
segnalazione_copiate: _translated_62_
segnalazione_duplicate: _translated_62.1_
segnalazione_osservate: _translated_63_
segnalazione_osservi: _translated_64_
segnalazione_Osserva: _translated_65_
segnalazione_osservatore: _translated_66_
segnalazione_Osservatore: _translated_67_
segnalazione_osservatori: _translated_68_
segnalazione_Osservatori: _translated_69_
segnalazione_osservatore_un: _translated_70_
segnalazione_Dimentica: _translated_71_
segnalazione_assegnare: _translated_72_
segnalazione_assegnata: _translated_73_
segnalazione_Assegnata: _translated_74_
segnalazione_assegnate: _translated_75_
segnalazione_assegnare: _translated_76_
segnalazione_assegnatario: _translated_77_
segnalazione_Assegnatario: _translated_78_
segnalazione_Assegnatari: _translated_79_
segnalazione_Assegnatario_agg: _translated_80_
segnalazione_assegnatario_lo: _translated_81_
segnalazione_assegn_dello: _translated_82_
segnalazione_categoria: _translated_83_
segnalazione_categorie: _translated_84_
segnalazione_Categoria: _translated_85_
segnalazione_Categorie: _translated_86_
segnalazione_categoria_la: _translated_87_
segnalazione_categoria_Nuova: _translated_88_
segnalazione_categoria_questa: _translated_89_
segnalazione_stato: _translated_90_
segnalazione_stati: _translated_91_
segnalazione_Stato: _translated_92_
segnalazione_Stati: _translated_93_
segnalazione_stato_lo: _translated_94_
segnalazione_stato_Nessuno: _translated_95_
segnalazione_stato_Nuovo: _translated_96_
segnalazione_stati_Nuovi: _translated_97_
segnalazione_stato_applicato: _translated_98_
segnalazione_stato_aggiornato: _translated_99_
segnalazione_stato_predefinito: _translated_100_
segnalazione_stato_configurato: _translated_101_
segnalazione_stato_attivo: _translated_102_
segnalazione_stato_usati: _translated_103_
segnalazione_stato_In_elab: _translated_104_
segnalazione_stato_Risolto: _translated_105_
segnalazione_stato_Commenti: _translated_106_
segnalazione_stato_Chiuso: _translated_107_
segnalazione_stato_Rifiutato: _translated_108_
segnalazione_nota: _translated_109_
segnalazione_note: _translated_110_
segnalazione_Nota: _translated_111_
segnalazione_Note: _translated_112_
segnalazione_nota_la: _translated_113_
segnalazione_nota_le: _translated_114_
segnalazione_nota_una: _translated_115_
segnalazione_nota_le_mie: _translated_116_
segnalazione_nota_aggiunta: _translated_117_
segnalazione_nota_salvata: _translated_118_
segnalazione_nota_precedenti: _translated_119_
segnalazione_nota_mantenute: _translated_120_
segnalazione_nota_private: _translated_121_
segnalazione_Tracker: _translated_122_
segnalazione_tracker: _translated_123_
segnalazione_tracker_plurale: _translated_124_
segnalazione_Tracker_plurale: _translated_125_
segnalazione_tracker_i: _translated_126_
segnalazione_tracker_Nuovo: _translated_127_
segnalazione_tracker_un: _translated_128_
segnalazione_tracker_questo: _translated_129_
segnalazione_tracker_Questo: _translated_130_
segnalazione_tracker_nessun: _translated_131_
segnalazione_tracker_Tutti: _translated_132_
segnalazione_tracker_associato: _translated_133_
segnalazione_tracker_eliminato: _translated_134_
segnalazione_tracker_finali: _translated_135_
segnalazione_Priorita: _translated_136_
segnalazione_priorita_agg: _translated_137_
tempo_Attivita: _translated_138_
diario_Attivita: _translated_139_
progetto: _translated_140_
progetti: _translated_141_
Progetto: _translated_142_
Progetti: _translated_143_
progetto_il: _translated_144_
progetto_Il: _translated_145_
progetto_i: _translated_146_
progetto_I: _translated_147_
progetto_un: _translated_148_
progetto_al: _translated_149_
progetto_dei: _translated_150_
progetto_del: _translated_151_
progetto_nel: _translated_152_
progetto_degli: _translated_153_
progetto_allo_stesso: _translated_154_
progetto_ad_uno_dei_miei: _translated_155_
progetto_i_suoi: _translated_156_
progetto_miei: _translated_157_
progetto_tutti: _translated_158_
progetto_Tutti: _translated_159_
progetto_nuovi: _translated_160_
progetto_Nuovo: _translated_161_
progetto_altri: _translated_162_
progetto_nessun: _translated_163_
progetto_questo: _translated_164_
progetto_Questo: _translated_165_
progetto_Ultimi: _translated_166_
progetto_registrati: _translated_167_
progetto_pubblici: _translated_168_
progetto_selezionati: _translated_169_
progetto_visibili: _translated_170_
progetto_chiuso: _translated_171_
progetto_chiusi: _translated_172_
progetto_archiviato: _translated_173_
progetto_attivo: _translated_174_
progetto_padre: _translated_175_
progetto_stato: _translated_176_
progetto_privo: _translated_177_
progetto_diversi: _translated_178_
sottoprogetto: _translated_179_
Sottoprogetto: _translated_180_
sottoprogetti: _translated_181_
Sottoprogetti: _translated_182_
ruolo_Gestore: _translated_183_
ruolo_Sviluppatore: _translated_184_
ruolo_Segnalatore: _translated_185_
